FROM node:10.17.0-alpine

# Create directory for app
#WORKDIR /app

# Install app dependencies
# A wildcard is used to ensure both package.js and package-lock.json are copied
# if available
#COPY package*.json ./app/
#RUN npm install

# Bundle app source
#ADD . /app

# Expose on port 3000
#EXPOSE 3000

# Run the server
#CMD ["node", "index.js"]
